### ISSUE TITLE
CI: only release when tests succeed and on master

### ISSUE THREAD

**Issue by Addono** [rokubun/jason-sdk-android#2]
Your current CI will attempt to publish to [Bintray for PRs](https://github.com/rokubun/jason-sdk-android/pull/1/checks?check_run_id=1169822175) - which will fail for remote users as they do not have access to secrets - I assume this is unintended, but maybe you support snapshots or pre-releases 🤷 . You can use the `if` keyword to skip the publish step for PRs.

In addition, the publish job will run irregardless of whether test failed or not, you can use the `needs` keyword to specify which jobs need to succeed before the publish job runs, e.g. 
https://github.com/Addono/container-registry-proxy/blob/f0ecea2cf25b3819c24175b322d1ed0d6ce0b7fa/.github/workflows/release.yml#L48.

**Comment by alexlopezc** [comment]
Hi,

Thanks for the commit and the suggestion, we have added an if condition based on the name of the repository, only the repository rokubun/jason-sdk-android will execute the publish stage.

Anyway, we have to review the publish stage since it is failing, so once fixed, we will add the needs keyword as you have suggested.

We are completely open to more suggestions, so do not hesitate to open more issues based on your experience with the SDK.

**Comment by Addono** [comment]
> We are completely open to more suggestions, so do not hesitate to open more issues based on your experience with the SDK.

Sure, will do!

> Anyway, we have to review the publish stage since it is failing, so once fixed, we will add the needs keyword as you have suggested.

👌  Since it's on your radar I will close this one.
